- Jika akan menjalankan file java nya, lakukan peritah di command line pada direktory file java yang akan dijalankan. 
- Perintah nya yaitu: 
    - ```javac *.java```
    - ```java namafilejava.java```